# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chatbot.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rchatbot.proto\x12\x07\x63hatbot\"$\n\x0fPDFPathsRequest\x12\x11\n\tpdf_paths\x18\x01 \x03(\t\"1\n\x10PDFPathsResponse\x12\r\n\x05reply\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x03(\t\"\x1e\n\x0b\x43hatRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1d\n\x0c\x43hatResponse\x12\r\n\x05reply\x18\x01 \x01(\t2\x95\x01\n\x0e\x43hatbotService\x12\x45\n\x0cSendPDFPaths\x12\x18.chatbot.PDFPathsRequest\x1a\x19.chatbot.PDFPathsResponse\"\x00\x12<\n\x0bSendMessage\x12\x14.chatbot.ChatRequest\x1a\x15.chatbot.ChatResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chatbot_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PDFPATHSREQUEST']._serialized_start=26
  _globals['_PDFPATHSREQUEST']._serialized_end=62
  _globals['_PDFPATHSRESPONSE']._serialized_start=64
  _globals['_PDFPATHSRESPONSE']._serialized_end=113
  _globals['_CHATREQUEST']._serialized_start=115
  _globals['_CHATREQUEST']._serialized_end=145
  _globals['_CHATRESPONSE']._serialized_start=147
  _globals['_CHATRESPONSE']._serialized_end=176
  _globals['_CHATBOTSERVICE']._serialized_start=179
  _globals['_CHATBOTSERVICE']._serialized_end=328
# @@protoc_insertion_point(module_scope)
